name: Laravel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run Docker containers
        run: docker-compose up -d --build
        
      - name: Run composer install
        run: docker-compose run --rm app composer install

      - name: Copy .env.example to .env
        run: docker-compose run --rm app cp .env.example .env

      - name: Generate application key
        run: docker-compose run --rm app php artisan key:generate

      - name: Run migrations
        run: docker-compose run --rm app php artisan migrate

      - name: Run tests
        run: docker-compose run --rm app php artisan test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Build and start Docker containers
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-27-230-216.ap-southeast-2.compute.amazonaws.com 'cd /var/www/laravel && git pull origin main && composer install && sudo docker compose up --build -d'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
