name: CI for Laravel with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run Docker containers
        run: docker-compose up -d --build

      - name: Wait for app container to be ready
        run: |
          docker-compose exec app sh -c 'until nc -z localhost 9000; do echo "Waiting for app..."; sleep 3; done'
          
      - name: Run composer install
        run: docker-compose exec app composer install

      - name: Copy .env.example to .env
        run: docker-compose exec app cp .env.example .env

      - name: Generate application key
        run: docker-compose exec app php artisan key:generate

      - name: Run migrations
        run: docker-compose exec app php artisan migrate

      - name: Run tests
        run: docker-compose exec app php artisan test
